color: null
fieldLayouts:
  2c85b916-cde3-4f4a-a45b-7df51bfd7a5f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-07T03:57:32+00:00'
            elementCondition: null
            fieldUid: a44287f8-d6ed-4f2c-8a63-0c1312ef236e # Image
            handle: fallbackImage
            includeInCards: false
            instructions: null
            label: 'Fallback Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0dcb109c-f907-4869-9278-8679de4850dc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: bc4c53fd-5da6-434f-8b07-8bcc6776952a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-07T03:57:45+00:00'
            elementCondition: null
            fieldUid: c372dc4c-2ba0-4569-89d6-b9e5d3641621 # GTM-Head
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 25c5ba43-cf5d-4863-8682-7812c61e2fef
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-07T03:57:45+00:00'
            elementCondition: null
            fieldUid: 1722d8e6-c1d8-4e9c-824e-c97bb31fc8e6 # GTM-Body
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 41cbe6d0-1010-4e27-a011-d46a04eea37f
            userCondition: null
            warning: null
            width: 100
        name: GTM-Codes
        uid: b883e8f0-349c-4206-8d15-2165487a7299
        userCondition:
          class: craft\elements\conditions\users\UserCondition
          conditionRules:
            -
              class: craft\elements\conditions\users\AdminConditionRule
              uid: 724b5dae-7ea4-4a96-9b8f-9f93b5a922f2
              value: true
          elementType: craft\elements\User
          fieldContext: global
handle: siteSettings
hasTitleField: false
icon: gear
name: 'Site Settings'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
