color: null
fieldLayouts:
  139a4c4d-9cb0-4666-b436-82a766732e2b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-01-01T15:40:28+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 561621e1-1274-4e28-88cf-8373bbc1f0fc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-01T15:44:53+00:00'
            elementCondition: null
            fieldUid: a09567f7-d67a-4f76-9cf0-9eb34460bd9c # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 69139ff2-0bd2-4b5c-8d32-b130bfe8ce54
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-01T15:44:53+00:00'
            elementCondition: null
            fieldUid: 3aa3d7e4-4b79-4179-bbd5-3e31157cbf44 # Verse Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f768b2b1-a15e-48c9-b339-534314d5523e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-01T15:56:17+00:00'
            elementCondition: null
            fieldUid: a44287f8-d6ed-4f2c-8a63-0c1312ef236e # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6c230006-0030-45f1-b182-9c18a0c513ef
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: dcc3301e-a3e3-4a83-a1a2-333ea2a205ea
        userCondition: null
handle: verseOfTheDay
hasTitleField: true
icon: address-book
name: 'Verse of The Day'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
