headingLevels:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
name: Full
options:
  alignment:
    options:
      - left
      - right
  fontSize:
    options:
      - tiny
      - small
      - big
      - huge
  heading:
    options:
      -
        class: ck-heading_paragraph
        model: paragraph
        title: Paragraph
      -
        class: ck-heading_heading1
        model: heading1
        title: 'Heading 1'
        view: h1
      -
        class: ck-heading_heading2
        model: heading2
        title: 'Heading 2'
        view: h2
  style:
    definitions:
      -
        classes:
          - red-heading
        element: h2
        name: 'Red heading'
      -
        classes:
          - vibrant-code
        element: pre
        name: 'Vibrant code'
      -
        classes:
          - marker
        element: span
        name: Marker
toolbar:
  - sourceEditing
  - code
  - heading
  - style
  - bold
  - italic
  - underline
  - strikethrough
  - subscript
  - superscript
  - link
  - fontSize
  - fontFamily
  - mediaEmbed
  - fontColor
  - insertImage
  - htmlEmbed
  - blockQuote
  - insertTable
  - alignment
  - bulletedList
  - numberedList
  - todoList
  - outdent
  - indent
  - pageBreak
  - selectAll
