columnSuffix: null
handle: isLive
instructions: null
name: 'Is Live'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
