dateModified: 1738007012
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: '*'
      tableAttributes:
        - slug
        - revisionCreator
        - dateUpdated
        - link
      type: native
    -
      heading: General
      type: heading
    -
      disabled: false
      key: 'single:5611e98d-93ec-4bd4-95dd-18f282b8c5e8' # Home
      tableAttributes:
        - slug
        - revisionCreator
        - dateUpdated
        - link
      type: native
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:45b7c78f-587d-441b-bbd1-605ca629d0bd' # Pages
      tableAttributes:
        - slug
        - revisionCreator
        - dateUpdated
        - link
      type: native
    -
      disabled: false
      key: 'single:5d236e94-b6a8-472c-9296-a5c992cdd49a' # Contact
      tableAttributes:
        - slug
        - revisionCreator
        - dateUpdated
        - link
      type: native
    -
      defaultSort:
        - id
        - asc
      defaultViewMode: cards
      disabled: false
      key: 'single:6f79e12f-9d80-4f17-ae51-5160127975ec' # Site Settings
      tableAttributes:
        - id
        - postDate
        - expiryDate
        - link
      type: native
    -
      heading: News
      type: heading
    -
      disabled: false
      key: 'single:4c32edae-2824-4f0f-b38b-2477d2500dfe' # News
      tableAttributes:
        - slug
        - revisionCreator
        - dateUpdated
        - link
      type: native
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:c576870d-abd8-46aa-8fe5-cdd12c40dfa8' # News Entries
      tableAttributes:
        - id
        - slug
        - revisionCreator
        - dateUpdated
        - link
      type: native
    -
      key: 'section:01faae48-e031-4496-af0c-89de7f12eccd' # News categories
      type: native
    -
      heading: Account
      type: heading
    -
      disabled: false
      key: 'single:361daec5-5ea3-4d9f-957f-f39c78bb595e' # Profile
      tableAttributes:
        - slug
        - revisionCreator
        - dateUpdated
        - link
      type: native
    -
      disabled: false
      key: 'single:c25b1e19-dca6-4ab5-a776-a043f6ee4c82' # Login
      tableAttributes:
        - slug
        - revisionCreator
        - dateUpdated
        - link
      type: native
    -
      disabled: false
      key: 'single:684ece64-c23a-4abf-9574-f2c053d496e8' # Register
      tableAttributes:
        - slug
        - revisionCreator
        - dateUpdated
        - link
      type: native
    -
      disabled: false
      key: 'single:dca2ac05-7833-41de-b7b4-a737c090575c' # Confirm your account
      tableAttributes:
        - slug
        - revisionCreator
        - dateUpdated
        - link
      type: native
    -
      disabled: false
      key: 'single:d5601a1f-a33e-4c5a-b7af-1f29347149ca' # Registration completed
      tableAttributes:
        - slug
        - revisionCreator
        - dateUpdated
        - link
      type: native
    -
      disabled: false
      key: 'single:1c4e3f0f-ca9b-474d-a460-48f45133c763' # Forgot password
      tableAttributes:
        - slug
        - revisionCreator
        - dateUpdated
        - link
      type: native
    -
      disabled: false
      key: 'single:53c1af4c-0fbd-4811-a028-67fed65195b9' # Forgot Password Confirmation
      tableAttributes:
        - slug
        - revisionCreator
        - dateUpdated
        - link
      type: native
    -
      disabled: false
      key: 'single:8e583282-1fec-4444-822f-37b2d5961f28' # Set Password
      tableAttributes:
        - slug
        - revisionCreator
        - dateUpdated
        - link
      type: native
    -
      disabled: false
      key: 'single:4703bf34-5e13-4da1-aff6-d04c0bba024b' # Set Password Confirmation
      tableAttributes:
        - slug
        - revisionCreator
        - dateUpdated
        - link
      type: native
    -
      disabled: false
      key: 'single:05aba0e3-e1de-4bf3-8a07-5c9f3ef9475c' # Edit profile
      tableAttributes:
        - slug
        - revisionCreator
        - dateUpdated
        - link
      type: native
    -
      disabled: false
      key: 'single:af69e9a2-96df-4fa9-8cc3-2728ec4fc632' # Edit password
      tableAttributes:
        - slug
        - revisionCreator
        - dateUpdated
        - link
      type: native
    -
      heading: Other
      type: heading
    -
      disabled: false
      key: 'single:36895330-a28e-477f-9327-bdbe66dabf99' # Cookie policy
      tableAttributes:
        - slug
        - revisionCreator
        - dateUpdated
        - link
      type: native
    -
      disabled: false
      key: 'single:c2198cbb-f6e1-478a-ab4a-bbbaea43ce0e' # Privacy policy
      tableAttributes:
        - slug
        - revisionCreator
        - dateUpdated
        - link
      type: native
    -
      key: 'single:99a435d2-9c12-4ef6-8b3b-2a9915d4216b' # Accessibility Statement
      type: native
    -
      disabled: false
      key: 'single:4750849d-9328-4d3e-956d-9d317da5e6eb' # Page not found
      tableAttributes:
        - slug
        - revisionCreator
        - dateUpdated
        - link
      type: native
    -
      disabled: false
      key: 'single:e3bed4e1-82ae-45e8-908c-0a6669141b31' # Search results
      tableAttributes:
        - slug
        - revisionCreator
        - dateUpdated
        - link
      type: native
    -
      disabled: false
      key: 'single:fa6e0764-a31c-4304-a4d7-76bd3a679e3e' # 503
      tableAttributes:
        - slug
        - revisionCreator
        - dateUpdated
        - link
      type: native
email:
  fromEmail: $SYSTEM_EMAIL
  fromName: $SYSTEM_NAME
  replyToEmail: null
  template: _mail/_layout
  transportSettings:
    command: '/usr/sbin/sendmail -bs'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  files:
    hasUrls: true
    name: Files
    settings:
      path: '@webroot/files'
    type: craft\fs\Local
    url: '@baseUrl/files/'
meta:
  __names__:
    1c4e3f0f-ca9b-474d-a460-48f45133c763: 'Forgot password' # Forgot password
    1e4267e1-8d5f-4312-8458-86b19bc17d74: 'Text (2 columns)' # Text (2 columns)
    1ea43556-c1c6-4ae7-9c49-48498a82f797: 'CK Editor - Extended' # CK Editor - Extended
    01faae48-e031-4496-af0c-89de7f12eccd: 'News categories' # News categories
    2a768305-5971-43c0-a2f4-415e648c6a45: Category # Category
    2e4b3bb0-26e4-47d2-9445-54401a221c63: 'X (Twitter)' # X (Twitter)
    2ef0df1a-8133-4216-849b-430b5a1db7c6: Breadcrumbs # Breadcrumbs
    2f8a6ddc-4ab7-4f9f-a2ea-72c6cb387f38: 'Overview description' # Overview description
    3aa3d7e4-4b79-4179-bbd5-3e31157cbf44: 'Verse Link' # Verse Link
    3b5e9f06-375c-4359-bdab-e633650a63d4: Full # Full
    4a2bad07-8d89-4689-b0bf-774eed764660: 'Overview title' # Overview title
    4c32edae-2824-4f0f-b38b-2477d2500dfe: News # News
    4cba9503-9b51-475c-b899-328b2bcd3448: DJs # DJs
    5a25f3e9-a180-4a29-aa41-8721fbf815b9: 'Optimized Content' # Optimized Content
    05aba0e3-e1de-4bf3-8a07-5c9f3ef9475c: 'Edit profile' # Edit profile
    5d236e94-b6a8-472c-9296-a5c992cdd49a: Contact # Contact
    5d7250f9-a00c-4732-a743-b46bb5d11646: 'CK Editor - Standard' # CK Editor - Standard
    5dbe5a67-b60b-4529-a095-facb9b24a39b: Table # Table
    6ca94949-c3f4-465d-88c7-3d4736d97ed4: Address # Address
    6f79e12f-9d80-4f17-ae51-5160127975ec: 'Site Settings' # Site Settings
    7b5ab248-6255-4b42-88bc-80c1dee62b20: 'Call To Action' # Call To Action
    7d23b02c-ad1d-44a8-9751-35fbdcc38963: Standard # Standard
    08b5c138-4286-4da2-b4b2-da7c919ebbae: Countdown # Countdown
    8c9b2c5d-02c2-4105-83ed-93563621e752: 'Position Left/Right' # Position Left/Right
    8dae44c9-d581-490d-b484-cfb0a86d8212: Locations # Locations
    8e583282-1fec-4444-822f-37b2d5961f28: 'Set Password' # Set Password
    8ff8437a-a38f-47f0-b489-1701614eec3f: 'Header image' # Header image
    9a0dd6a8-9ebb-44f8-a62a-03f12bf2a504: Author # Author
    9abed6d9-3042-4dd4-add0-3115a6e2693b: 'Image position' # Image position
    9bc4b9f2-7fc6-48b0-a3df-8e9c061a70c6: Instagram # Instagram
    9f39fdda-793c-4506-9dd4-e764d46cad28: 'Contentbuilder Page' # Contentbuilder Page
    15ed2b72-8955-4cec-93f8-9736a9e50e80: 'Overview image' # Overview image
    24bd0074-b53d-404d-9285-a0be9f26bbd4: Overview # Overview
    25f93ead-d3f6-4049-ba98-6378754f4289: Extended # Extended
    39f07216-d49a-4917-b05e-bec26f425843: Caption # Caption
    45b7c78f-587d-441b-bbd1-605ca629d0bd: Pages # Pages
    53c1af4c-0fbd-4811-a028-67fed65195b9: 'Forgot Password Confirmation' # Forgot Password Confirmation
    56d715d0-6a9d-4562-9c66-e5b4caad7f44: 'Content Builder' # Content Builder
    60b48ff5-1ab2-471b-8592-cdc623e0882c: 'Optimized Text Image' # Optimized Text Image
    61cbb04c-ab3f-421e-bb8f-9e81ecc0da41: Site # Site
    71d59fcf-f766-4db1-a6fe-87bf1ce1b1ba: 'Call to action' # Call to action
    74a30650-eb90-462f-a104-de1d41ac8221: Form # Form
    75c71ec6-7c59-460d-bac3-80ae2ee887a5: 'Site Settings' # Site Settings
    82edb6db-a497-4e37-8c25-5d4d210f0c81: 'Search keywords' # Search keywords
    89c47888-bddf-4633-9352-1d5dc3bb452f: Home # Home
    99a435d2-9c12-4ef6-8b3b-2a9915d4216b: 'Accessibility Statement' # Accessibility Statement
    109f5d44-e366-49e7-826d-6b13de779861: News # News
    131a4f6d-f00f-4238-b846-dd504bf669fe: Simple # Simple
    0207f1a0-8ec0-4b87-9197-c1d5a9a7b61d: 'Optimized Overview' # Optimized Overview
    361daec5-5ea3-4d9f-957f-f39c78bb595e: Profile # Profile
    0396f80c-a192-4beb-a6e7-075075cf0f70: Image # Image
    498ec76d-4c69-405d-b05a-6aa5985e8c9e: 'Verse of The Day' # Verse of The Day
    683cbd88-ef11-45e0-83b4-e20d03f6ea6b: 'Image width' # Image width
    684ece64-c23a-4abf-9574-f2c053d496e8: Register # Register
    776fa716-10bb-48bb-ae08-28870f9d77e7: Entries # Entries
    837a8cff-ff1c-4c10-9ce2-5d3bc31b0c4b: 'Is Live' # Is Live
    838aabf9-a30e-4616-ad7c-b89fe15d7cae: 'Title (Anchor)' # Title (Anchor)
    979c3eeb-f99a-4ca1-bcbe-ce9298a4e4ca: 'Public Files' # Public Files
    1722d8e6-c1d8-4e9c-824e-c97bb31fc8e6: GTM-Body # GTM-Body
    02475d2d-9d04-4f95-ae81-c45fac274e41: Live # Live
    3196b984-5af4-44dd-a6db-ac2c8f7924d9: 'Content Managers' # Content Managers
    03498d1a-eb01-4cb2-9e2b-623015ed0d85: 'Link Style' # Link Style
    3857f4aa-a319-44ec-8b5e-d907d3d1bf31: 'Background Color' # Background Color
    4703bf34-5e13-4da1-aff6-d04c0bba024b: 'Set Password Confirmation' # Set Password Confirmation
    5611e98d-93ec-4bd4-95dd-18f282b8c5e8: Home # Home
    6221c006-75b9-4fa5-a352-4cd4317fb5d7: Youtube # Youtube
    7256a782-20ff-4771-9d85-ed3f49e13ef4: Quote # Quote
    9084b802-1468-4763-a867-2e4b1ebd3f09: 'Show larger version in popup' # Show larger version in popup
    37471b2c-6c44-4b1a-bc50-3788e9de05d5: Hero # Hero
    44549f86-4264-4c94-964c-a927c53c2a38: 'Author Image' # Author Image
    66954acb-77ba-4c75-9659-f3976770df07: 'CK Editor - Simple' # CK Editor - Simple
    072209d1-1c68-4ee5-9a66-a209b518da6d: Mail # Mail
    197566c6-94bb-4e67-86d7-8945f2589a1d: 'Optimized Hero' # Optimized Hero
    209777db-293c-48b6-9897-1fe97b278510: Video # Video
    685530fc-e1f1-4be1-813b-ebf9ac3aa108: SEO # SEO
    724561c2-845a-427f-b005-e0c2a35e0112: 'Placeholder Image' # Placeholder Image
    4750849d-9328-4d3e-956d-9d317da5e6eb: 'Page not found' # Page not found
    6122281a-7d92-44b0-bef8-296775631068: 'Simple page (Title/Intro/SEO)' # Simple page (Title/Intro/SEO)
    36895330-a28e-477f-9327-bdbe66dabf99: 'Cookie policy' # Cookie policy
    72249346-bd02-4556-9736-1139ed941344: Quote # Quote
    95920915-f806-4fbc-9c22-979ec9085fe8: 'Text + Video' # Text + Video
    a09567f7-d67a-4f76-9cf0-9eb34460bd9c: Description # Description
    a5c5b738-ae52-4b69-a209-d515d2e7b71a: 'Public Schema' # Public Schema
    a44287f8-d6ed-4f2c-8a63-0c1312ef236e: Image # Image
    af69e9a2-96df-4fa9-8cc3-2728ec4fc632: 'Edit password' # Edit password
    b4e0e49a-bcd4-4d67-80ad-09ea0d807bd8: 'CK Editor - Table' # CK Editor - Table
    b5de6dcf-80e6-48e2-b846-0dab7f35c4c8: 'Intro Text' # Intro Text
    b13fc4bd-af47-4f5c-b349-05e9e24dfecc: 'Search results' # Search results
    bb709734-1225-40d5-b983-249a24782f4c: DJs # DJs
    bcf87482-b5f3-4be6-9a63-153f0458466b: 'Image Copyright' # Image Copyright
    c7f05fcd-6b9c-44dd-baee-f3e9cd0c47ac: 'News Category' # News Category
    c25b1e19-dca6-4ab5-a776-a043f6ee4c82: Login # Login
    c70bb41d-9301-4a5b-852a-d14fb87046d8: 'Contact Form' # Contact Form
    c372dc4c-2ba0-4569-89d6-b9e5d3641621: GTM-Head # GTM-Head
    c2198cbb-f6e1-478a-ab4a-bbbaea43ce0e: 'Privacy policy' # Privacy policy
    c34194a8-1ee7-46cc-809d-03a1507d2384: Live # Live
    c576870d-abd8-46aa-8fe5-cdd12c40dfa8: 'News Entries' # News Entries
    c5302424-61ab-45cb-a6e2-3185645ccc8a: 'Verse of The Day' # Verse of The Day
    cd736fb3-c9b7-4ce1-88a8-da8b64249eb1: Images # Images
    ce1fab3c-0b02-49d8-8d8f-1bab2d7c05e2: LinkedIn # LinkedIn
    d0206206-c880-45f7-848e-0a4baa623a7e: Default # Default
    d3b383b6-5ad7-494f-bc13-c06a53a5e5e9: 'News Overview' # News Overview
    d66ffcef-8ccc-4e89-9e36-bce49e0dd17a: Video # Video
    d5601a1f-a33e-4c5a-b7af-1f29347149ca: 'Registration completed' # Registration completed
    d86336d6-7efa-44f9-9a10-8619c79beeca: 'Text (+ Image)' # Text (+ Image)
    dca2ac05-7833-41de-b7b4-a737c090575c: 'Confirm your account' # Confirm your account
    dd939721-6ae7-4b69-a3a3-7d9dbe9890c8: Default # Default
    e3bed4e1-82ae-45e8-908c-0a6669141b31: 'Search results' # Search results
    e57cf13b-f9cb-484a-8093-a897fa43eb68: $SYSTEM_NAME # $SYSTEM_NAME
    e48813cd-24dc-4b06-a97d-2a95520dcc24: Phone # Phone
    ed516703-9411-446f-8ce9-d66e9c48839a: 'Hero Block' # Hero Block
    f2d8b097-d5ba-4224-9736-4dc41bd6580f: Contact # Contact
    f2d33237-c7de-4590-9683-7efe6594ebbd: 'Custom Table' # Custom Table
    f694fce1-48ca-4bfe-9fba-196195547a36: Facebook # Facebook
    f3211a4e-d5f8-4514-a372-c5b8cfc2c44a: Form # Form
    f5752ee4-d6a4-4a44-b353-f2b48770c9be: New # New
    f936530d-29a5-4460-9ccd-b586bfb25329: 'Call to actions' # Call to actions
    fa6e0764-a31c-4304-a4d7-76bd3a679e3e: '503' # 503
plugins:
  calendar:
    edition: lite
    enabled: true
    licenseKey: 9S3YAA2HI5845XN8A3A2DDHX
    schemaVersion: 5.0.1
    settings:
      allDay: false
      authoredEventEditOnly: false
      defaultView: month
      demoBannerDisabled: true
      descriptionFieldHandle: null
      eventDuration: 60
      firstDayOfWeek: -1
      guestAccess: null
      locationFieldHandle: null
      overlapThreshold: 5
      pluginName: null
      quickCreateEnabled: true
      showDisabledEvents: true
      showMiniCal: true
      timeFormat: auto
      timeInterval: 30
  carbon-tracker:
    edition: standard
    enabled: true
    schemaVersion: 1.1.0
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  config-values-field:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  cookie-banner:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  cp-clearcache:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  cp-css:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
    settings:
      additionalCss: "#global-sidebar {\r\n    background-color: #013852;\r\n    color: #ffffff;\r\n}\r\n"
      cacheBusting: true
      cssFile: ''
  cp-field-inspect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  cp-nav:
    edition: standard
    enabled: true
    schemaVersion: 2.0.11
  craft-sentry:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  dumper:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  element-index-defaults:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  formie:
    edition: standard
    enabled: true
    licenseKey: AFT4HYBZPFF2KVVYL7L81J6J
    schemaVersion: 3.4.8
  guide:
    edition: lite
    enabled: true
    schemaVersion: 5.0.0
    settings:
      assetVolume: ''
      clientName: 'Greentree Radio'
      editPageLocation: slideout
      enableGuideCss: '0'
      enableGuideJavascript: '0'
      fun: '1'
      guideButtonLabel: ''
      myCompanyName: 'Greentree Radio'
      projectName: 'Greentree Radio'
      registerGuideCss: true
      registerGuideJavascript: true
      renderMarkdownDefault: '0'
      templatePath: _guide
  hyper:
    edition: standard
    enabled: true
    licenseKey: 7APWPVQGV9SY12W2SVRFFJHF
    schemaVersion: 1.0.0
  image-optimize:
    edition: standard
    enabled: true
    licenseKey: DSY6RYUDQ6WKIRD7PJXDWM6I
    schemaVersion: 1.0.0
  image-resizer:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  knock-knock:
    edition: standard
    enabled: true
    schemaVersion: 1.1.1
  navigate:
    edition: standard
    enabled: true
    licenseKey: W0IKODJ6K7LS96O85NEDTRWT
    schemaVersion: 2.4.0
  obfuscator:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  olivemenus:
    edition: standard
    enabled: true
    schemaVersion: 1.1.11
  password-policy:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  position-fieldtype:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  postmark:
    edition: standard
    enabled: true
    schemaVersion: 2.0.1
  seo-fields:
    edition: standard
    enabled: true
    licenseKey: XB7DG1I5LAIKDG8ACFH9GK2Q
    schemaVersion: 4.0.0
  seomatic:
    edition: standard
    enabled: true
    licenseKey: MS4TR6Z6PLXJURKYG9XYWVFI
    schemaVersion: 3.0.12
  sprig:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
  tablemaker:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
  templatecomments:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  translate:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  upvote:
    edition: standard
    enabled: true
    licenseKey: O9XZH1OI2EPCT5WDGIU0ECQK
    schemaVersion: 2.0.0
    settings:
      allowDownvoting: true
      allowFontAwesome: false
      allowVoteRemoval: true
      debounceDelay: 200
      keepVoteLog: false
      preload: false
      requireLogin: true
  video-parser:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  width-fieldtype:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: $SYSTEM_NAME
  retryDuration: null
  schemaVersion: 5.6.0.2
  timeZone: America/Chicago
