currLabel: Meta
customIcon: null
enabled: true
handle: defaults
icon: null
layout: dd939721-6ae7-4b69-a3a3-7d9dbe9890c8 # Default
level: 2
newWindow: false
parent: feb9ffb8-e19f-46f8-a792-e7c8d27d6f16
prevLabel: Meta
prevLevel: 2
prevParent: feb9ffb8-e19f-46f8-a792-e7c8d27d6f16
prevUrl: seo-fields/defaults
sortOrder: 17
type: plugin
url: seo-fields/defaults
