currLabel: Entries
customIcon: null
enabled: true
handle: entries
icon: newspaper
layout: dd939721-6ae7-4b69-a3a3-7d9dbe9890c8 # Default
level: 1
newWindow: false
parent: null
prevLabel: Entries
prevLevel: 1
prevParent: null
prevUrl: entries
sortOrder: 2
type: craft
url: entries
