currLabel: Formie
customIcon: null
enabled: true
handle: formie
icon: /var/www/html/vendor/verbb/formie/src/icon-mask.svg
layout: dd939721-6ae7-4b69-a3a3-7d9dbe9890c8 # Default
level: 1
newWindow: false
parent: null
prevLabel: Formie
prevLevel: 1
prevParent: null
prevUrl: formie
sortOrder: 6
type: plugin
url: formie
