currLabel: 'Global SEO'
customIcon: null
enabled: true
handle: global
icon: null
layout: dd939721-6ae7-4b69-a3a3-7d9dbe9890c8 # Default
level: 2
newWindow: false
parent: d2fcdcff-4bb2-4832-99e9-a7aa354f13a9
prevLabel: 'Global SEO'
prevLevel: 2
prevParent: d2fcdcff-4bb2-4832-99e9-a7aa354f13a9
prevUrl: seomatic/global/general
sortOrder: 54
type: plugin
url: seomatic/global/general
