currLabel: GraphiQL
customIcon: null
enabled: true
handle: graphiql
icon: null
layout: dd939721-6ae7-4b69-a3a3-7d9dbe9890c8 # Default
level: 2
newWindow: true
parent: 2bc1bbad-057a-46d8-a536-86e9643ae95b
prevLabel: GraphiQL
prevLevel: 2
prevParent: 2bc1bbad-057a-46d8-a536-86e9643ae95b
prevUrl: graphiql
sortOrder: 28
type: craft
url: graphiql
