currLabel: GraphQL
customIcon: null
enabled: true
handle: graphql
icon: graphql
layout: dd939721-6ae7-4b69-a3a3-7d9dbe9890c8 # Default
level: 1
newWindow: false
parent: null
prevLabel: GraphQL
prevLevel: 1
prevParent: null
prevUrl: graphql
sortOrder: 25
type: craft
url: graphql
