currLabel: 'CMS Guide'
customIcon: null
enabled: true
handle: home
icon: null
layout: dd939721-6ae7-4b69-a3a3-7d9dbe9890c8 # Default
level: 2
newWindow: false
parent: 1d100655-bab5-43d5-892f-47c89249dfc5
prevLabel: 'CMS Guide'
prevLevel: 2
prevParent: 1d100655-bab5-43d5-892f-47c89249dfc5
prevUrl: guide
sortOrder: 12
type: plugin
url: guide
