currLabel: '404''s'
customIcon: null
enabled: true
handle: notfound
icon: null
layout: dd939721-6ae7-4b69-a3a3-7d9dbe9890c8 # Default
level: 2
newWindow: false
parent: feb9ffb8-e19f-46f8-a792-e7c8d27d6f16
prevLabel: '404''s'
prevLevel: 2
prevParent: feb9ffb8-e19f-46f8-a792-e7c8d27d6f16
prevUrl: seo-fields/not-found
sortOrder: 18
type: plugin
url: seo-fields/not-found
