currLabel: Schemas
customIcon: null
enabled: true
handle: schemas
icon: null
layout: dd939721-6ae7-4b69-a3a3-7d9dbe9890c8 # Default
level: 2
newWindow: false
parent: 2bc1bbad-057a-46d8-a536-86e9643ae95b
prevLabel: Schemas
prevLevel: 2
prevParent: 2bc1bbad-057a-46d8-a536-86e9643ae95b
prevUrl: graphql/schemas
sortOrder: 26
type: craft
url: graphql/schemas
