currLabel: SEOmatic
customIcon: null
enabled: true
handle: seomatic
icon: /var/www/html/vendor/nystudio107/craft-seomatic/src/icon-mask.svg
layout: dd939721-6ae7-4b69-a3a3-7d9dbe9890c8 # Default
level: 1
newWindow: false
parent: null
prevLabel: SEOmatic
prevLevel: 1
prevParent: null
prevUrl: seomatic
sortOrder: 52
type: plugin
url: seomatic
