currLabel: Settings
customIcon: null
enabled: true
handle: settings
icon: gear
layout: dd939721-6ae7-4b69-a3a3-7d9dbe9890c8 # Default
level: 1
newWindow: false
parent: null
prevLabel: Settings
prevLevel: 1
prevParent: null
prevUrl: settings
sortOrder: 30
type: craft
url: settings
