currLabel: Users
customIcon: null
enabled: true
handle: users
icon: user-group
layout: dd939721-6ae7-4b69-a3a3-7d9dbe9890c8 # Default
level: 1
newWindow: false
parent: null
prevLabel: Users
prevLevel: 1
prevParent: null
prevUrl: users
sortOrder: 4
type: craft
url: users
