currLabel: Utilities
customIcon: null
enabled: true
handle: utilities
icon: wrench
layout: dd939721-6ae7-4b69-a3a3-7d9dbe9890c8 # Default
level: 1
newWindow: false
parent: null
prevLabel: Utilities
prevLevel: 1
prevParent: null
prevUrl: utilities
sortOrder: 29
type: craft
url: utilities
