defaultPlacement: end
enableVersioning: true
entryTypes:
  - f2d8b097-d5ba-4224-9736-4dc41bd6580f # Contact
handle: contact
maxAuthors: 1
name: Contact
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  e57cf13b-f9cb-484a-8093-a897fa43eb68: # $SYSTEM_NAME
    enabledByDefault: true
    hasUrls: true
    template: _site/_contact
    uriFormat: '{slug}'
type: single
