defaultPlacement: end
enableVersioning: true
entryTypes:
  - c34194a8-1ee7-46cc-809d-03a1507d2384 # Live
handle: countdown
maxAuthors: 1
name: Countdown
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  e57cf13b-f9cb-484a-8093-a897fa43eb68: # $SYSTEM_NAME
    enabledByDefault: true
    hasUrls: true
    template: countdown.twig
    uriFormat: countdown
type: single
