defaultPlacement: end
enableVersioning: true
entryTypes:
  - d3b383b6-5ad7-494f-bc13-c06a53a5e5e9 # News Overview
handle: news
maxAuthors: 1
name: News
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  e57cf13b-f9cb-484a-8093-a897fa43eb68: # $SYSTEM_NAME
    enabledByDefault: true
    hasUrls: true
    template: _site/_news/_index
    uriFormat: '{slug}'
type: single
