defaultPlacement: end
enableVersioning: true
entryTypes:
  - 9f39fdda-793c-4506-9dd4-e764d46cad28 # Contentbuilder Page
handle: pageNotFound
maxAuthors: 1
name: 'Page not found'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primaire invoer-pagina'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  e57cf13b-f9cb-484a-8093-a897fa43eb68: # $SYSTEM_NAME
    enabledByDefault: true
    hasUrls: true
    template: '404'
    uriFormat: '404'
type: single
