defaultPlacement: end
enableVersioning: true
entryTypes:
  - b13fc4bd-af47-4f5c-b349-05e9e24dfecc # Search results
handle: searchResults
maxAuthors: 1
name: 'Search results'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  e57cf13b-f9cb-484a-8093-a897fa43eb68: # $SYSTEM_NAME
    enabledByDefault: true
    hasUrls: true
    template: _site/_searchResults.twig
    uriFormat: search-results
type: single
