defaultPlacement: end
enableVersioning: true
entryTypes:
  - 6122281a-7d92-44b0-bef8-296775631068 # Simple page (Title/Intro/SEO)
handle: setPassword
maxAuthors: 1
name: 'Set Password'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  e57cf13b-f9cb-484a-8093-a897fa43eb68: # $SYSTEM_NAME
    enabledByDefault: true
    hasUrls: true
    template: _site/_account/_passwordSet
    uriFormat: renew-password
type: single
