defaultPlacement: end
enableVersioning: true
entryTypes:
  - 9f39fdda-793c-4506-9dd4-e764d46cad28 # Contentbuilder Page
handle: systemOffline
maxAuthors: 1
name: '503'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  e57cf13b-f9cb-484a-8093-a897fa43eb68: # $SYSTEM_NAME
    enabledByDefault: true
    hasUrls: true
    template: '503'
    uriFormat: '503'
type: single
